name: Library Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: 'library-tests'
  cancel-in-progress: true

jobs:
  test-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Test TypeScript compilation
        run: |
          # Test that all TypeScript files compile
          npx tsc --noEmit
          echo "✅ All TypeScript files compile successfully"

      - name: Test type checking
        run: |
          # Test that type checking passes
          npm run type-check
          echo "✅ Type checking passed"

      - name: Run unit tests
        run: |
          # Run Jest unit tests
          npm test
          echo "✅ Unit tests passed"

      - name: Test build process
        run: |
          # Test that the build process works correctly
          npm run build
          echo "✅ Build process completed successfully"

      - name: Verify build output
        run: |
          # Verify that all expected build outputs exist
          ls -la dist/
          echo "✅ Build output verification completed"
